name: rust_builder
description: Build bridge for elcaju_core Rust crate.
version: 0.1.0

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.11.1

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
