// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Generate a new 12-word BIP39 mnemonic
String generateMnemonic() =>
    RustLib.instance.api.crateApiKeysGenerateMnemonic();

/// Convert a mnemonic to a 64-byte seed
Uint8List mnemonicToSeed({required String mnemonic}) =>
    RustLib.instance.api.crateApiKeysMnemonicToSeed(mnemonic: mnemonic);

/// Derive the public key (hex) from a secret key (hex)
String getPubKey({required String secret}) =>
    RustLib.instance.api.crateApiKeysGetPubKey(secret: secret);
