// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_creq_from_uri`, `parse_payment_request_inner`

/// Parsed payment request info exposed to Flutter.
/// CDK's FromStr auto-detects creqA (CBOR) vs creqB (Bech32m).
class PaymentRequestInfo {
  /// Raw encoded string (creqA... or CREQB1...)
  final String raw;

  /// Payment id
  final String? paymentId;

  /// Requested amount (in base unit)
  final BigInt? amount;

  /// Currency unit ("sat", "usd", etc.)
  final String? unit;

  /// Whether this is a single-use request
  final bool? singleUse;

  /// Accepted mints (empty = any mint)
  final List<String> mints;

  /// Human-readable description
  final String? description;

  /// Available transports
  final List<TransportInfo> transports;

  /// Whether NUT-10 spending conditions are required
  final bool hasNut10;

  const PaymentRequestInfo({
    required this.raw,
    this.paymentId,
    this.amount,
    this.unit,
    this.singleUse,
    required this.mints,
    this.description,
    required this.transports,
    required this.hasNut10,
  });

  /// Parse a payment request string (creqA, CREQB1, or bitcoin:?creq=).
  /// Supports NUT-18 (CBOR+base64) and NUT-26 (Bech32m) automatically.
  static PaymentRequestInfo parse({required String encoded}) => RustLib
      .instance
      .api
      .crateApiPaymentRequestPaymentRequestInfoParse(encoded: encoded);

  @override
  int get hashCode =>
      raw.hashCode ^
      paymentId.hashCode ^
      amount.hashCode ^
      unit.hashCode ^
      singleUse.hashCode ^
      mints.hashCode ^
      description.hashCode ^
      transports.hashCode ^
      hasNut10.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaymentRequestInfo &&
          runtimeType == other.runtimeType &&
          raw == other.raw &&
          paymentId == other.paymentId &&
          amount == other.amount &&
          unit == other.unit &&
          singleUse == other.singleUse &&
          mints == other.mints &&
          description == other.description &&
          transports == other.transports &&
          hasNut10 == other.hasNut10;
}

/// Transport info exposed to Flutter
class TransportInfo {
  /// "nostr" or "post"
  final String transportType;

  /// Target (nprofile or URL)
  final String target;

  const TransportInfo({required this.transportType, required this.target});

  @override
  int get hashCode => transportType.hashCode ^ target.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportInfo &&
          runtimeType == other.runtimeType &&
          transportType == other.transportType &&
          target == other.target;
}
